version: "3.8"
services:
  db:
    image: mysql:8
    container_name: nutrimate-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nutrimate
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
