version: "3.8"
services:
  db:
    image: mysql:8
    container_name: nutrimate-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nutrimate
    volumes:
    
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build: .
    container_name: nutrimate-backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    command: npm run dev
    volumes:
      - .:/app
    working_dir: /app

volumes:
  db_data:
